# Generated by Django 4.2.25 on 2025-10-02 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('links', models.TextField()),
                ('media', models.FileField(blank=True, null=True, upload_to='jobmedia/')),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('prodi', models.CharField(max_length=100)),
                ('angkatan', models.CharField(max_length=4)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('portofolio', models.FileField(blank=True, null=True, upload_to='portofolio/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('bidang', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReportQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu_ke', models.IntegerField()),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsCoop.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReportAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsCoop.weeklyreportquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsCoop.weeklyreportsession')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('supervisor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsCoop.perusahaan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filereport', models.FileField(upload_to='final_reports/')),
                ('tanggal_upload', models.DateField(auto_now_add=True)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utsCoop.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsCoop.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsCoop.evaluationquestion')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsCoop.mahasiswa'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsCoop.supervisor'),
        ),
        migrations.CreateModel(
            name='CoOpDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('applying', 'Applying'), ('progress', 'On Progress'), ('report', 'Report Required'), ('finished', 'Finished')], default='applying', max_length=20)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utsCoop.mahasiswa')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsCoop.supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='CoOpAccInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proofmentor', models.FileField(upload_to='proof_mentor/')),
                ('proofsptjm', models.FileField(upload_to='sptjm/')),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='utsCoop.mahasiswa')),
            ],
        ),
    ]
