# Generated by Django 4.2.25 on 2025-10-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsCoop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='jeniskelamin',
            field=models.CharField(default='Wanita', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='status',
            field=models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], default='Pria', max_length=20),
        ),
    ]
