# Generated by Django 4.2.25 on 2025-10-03 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utsCoop', '0002_mahasiswa_jeniskelamin_mahasiswa_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyreportanswer',
            old_name='answer',
            new_name='ilmu_berguna',
        ),
        migrations.RemoveField(
            model_name='weeklyreportanswer',
            name='question',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='is_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyreportanswer',
            name='ilmu_kurang',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreportanswer',
            name='jobdesk',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreportanswer',
            name='suasana',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklyreportsession',
            name='minggu_ke',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='EvaluationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('target_angkatan', models.CharField(help_text='e.g. 2021,2022', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(to='utsCoop.evaluationquestion')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_form',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='utsCoop.evaluationform'),
            preserve_default=False,
        ),
    ]
