# Generated by Django 4.2.25 on 2025-10-03 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utsCoop', '0005_remove_evaluationform_evaluation_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoOpRegistration',
            fields=[
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utsCoop.mahasiswa')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('placement_status', models.CharField(choices=[('pending_placement', 'Pending Placement Confirmation'), ('confirmed', 'Confirmed Placement')], default='pending_placement', max_length=50)),
                ('placement_deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoPlacementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
