# Generated by Django 4.2.25 on 2025-10-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utsCoop', '0007_jobapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
    ]
